version: '2'

# This compose file is just an example. Create your own to launch your own Aegir cluster

services:

  devmaster:
    image: devmaster
    ports:
      - 80:80
    hostname: devshop.local.computer
    links:
      - database
    depends_on:
      - database
    environment:
      MYSQL_ROOT_PASSWORD: strongpassword
    volumes:
        - ./devmaster-1.x:/var/aegir/devmaster-1.x
        - ./drush:/usr/share/drush/commands

  database:
    image: mariadb
    logging:
      driver: none
    environment:
      MYSQL_ROOT_PASSWORD: strongpassword