---
# for vars.RedHat.yml
apache_user: apache
apache_confd_path: /etc/httpd/conf.d/aegir.conf
apache_control: /usr/sbin/apachectl
apache_daemon: httpd

php_ini_path: /etc/php.ini
mysql_cnf_path: /etc/my.cnf
mysql_daemon: mariadb.service

supervisor_daemon: supervisord
supervisor_conf_path: /etc/supervisord.d

motd_path: /etc/motd

bashrc_path: /etc/bashrc