document_root: devshop-2.x
hooks:
  build: |
    drush make build-devshop.make devshop-2.x --prepare-install -y
    echo "\$databases['default']['default'] = array(
      'driver' => 'mysql',
      'database' => 'drupal',
      'username' => 'drupal',
      'password' => 'drupal',
      'host' => 'database',
    );" >> devshop-2.x/sites/default/settings.php
    
  enable_first: |
    drush {{alias}} site-install devmaster --account-mail=jon@opendevshop.com --site-name='OpenDevShop' -y

  # On environment:deploy
  deploy: |
    drush {{alias}} updb -y
    drush {{alias}} cc all
#
#docker_compose:
#  app_services:
#      image: jenkins
#          hostname: jenkins
#          ports:
#              - '*:8080'
#          volumes:
#              - '.:/var/jenkins_home'
