language: php

dist: bionic

sudo: required
git:
  depth: false
  quiet: true

branches:
  only:
    - 1.x

env:
  global:
    - ANSIBLE_VERBOSITY=3
    - DEVSHOP_VERSION=1.x
    - GITHUB_REF=$TRAVIS_PULL_REQUEST_BRANCH
    - GITHUB_HEAD_REF=$TRAVIS_PULL_REQUEST_BRANCH
    - SITE_HOSTS='dev.drup.devshop.travis dev.projectname.devshop.travis live.projectname.devshop.travis testenv.drpl8.devshop.travis dev.rootproject.devshop.local.computer devshop.local.computer'

  matrix:
    - OS_VERSION: ubuntu1804
      PHP_VERSION: 7.2

    - OS_VERSION: ubuntu1804
      PHP_VERSION: 7.3

    - OS_VERSION: ubuntu1804
      PHP_VERSION: 7.4

jobs:
  fast_finish: true
  allow_failures:
    - env: ALLOW_FAIL=true

addons:
  hosts:
    - devshop.travis
    - dev.projectname.devshop.travis
    - live.projectname.devshop.travis
    - dev.drpl8.devshop.travis
    - testenv.drpl8.devshop.travis
    - dev.rootproject.devshop.local.computer

services:
  - docker

before_install:

  # If TRAVIS_PULL_REQUEST_BRANCH variable is not empty, create a branch with the same name so the upgrade tests do not fail.
  # See https://github.com/opendevshop/devshop/issues/356
  # This is how Travis clones the codebase:
  #    git clone --depth=50 https://github.com/opendevshop/devshop.git opendevshop/devshop
  #    cd opendevshop/devshop
  #    git fetch origin +refs/pull/355/merge:
  #    git checkout -qf FETCH_HEAD
  #
  #  If this is a PR, the $TRAVIS_PULL_REQUEST_BRANCH is set, and we must recreate the PR branch locally.
  #  Otherwise, the upgrade test fails because `devshop self-update` tries to checkout the branch but there's no commits.
  - if [ ! -z "$TRAVIS_PULL_REQUEST_BRANCH" ]; then
      git remote add fork -f https://github.com/$TRAVIS_PULL_REQUEST_SLUG;
      git checkout -b $TRAVIS_PULL_REQUEST_BRANCH -t fork/$TRAVIS_PULL_REQUEST_BRANCH;
    fi
  - env
  - id -u
  - docker --version
  - docker-compose --version

install:
  # Prepare devshop CLI.
  - composer install --prefer-dist --no-progress --no-suggest

  # Prepare containers
  - |
    docker build . \
    --build-arg OS_VERSION \
    --build-arg ANSIBLE_EXTRA_VARS='php_version: ${PHP_VERSION}' \
    --build-arg ANSIBLE_VERBOSITY \
    --tag=devshop/server:local \

script:

  # Launch devshop server and run tests.
  - bin/robo up --test --skip-source-prep -v


after_failure:
  - docker-compose logs

notifications:
  slack: devshophq:pb05x3ZL3qumHs0RjqEXvYfA
