---
##
# Big thanks to geerlingguy!
# https://servercheck.in/blog/testing-ansible-roles-travis-ci-github

language: python
python: "2.7"
before_install:
 - sudo apt-get update -qq
 - sudo apt-get install -qq python-apt python-pycurl
install:

  # Install Ansible
  - pip install ansible

script:
  - cd installers/ansible
  - echo localhost > inventory

  # Syntax Check
  - ansible-playbook -i inventory --syntax-check playbook.yml

  # Run Playbook
  - ansible-playbook -i inventory playbook.yml --connection=local --sudo

  # Test for DevShop
  - curl http://localhost/

# Notify devshop IRC chatroom.
notifications:
  irc: "chat.freenode.net#devshop"
