sudo: required

env:
  # CentOS 6: Not supported yet.
  #- distribution: centos
  #  version: 6
  #  init: /sbin/init
  #  run_opts: ""
  # Ubuntu 12.04: Not supported yet.
  #- distribution: ubuntu
  #  version: 12.04
  #  init: /sbin/init
  #  run_opts: ""
  - test: CentOS 7 Apache
    distribution: centos
    version: 7
    init: /usr/lib/systemd/systemd
    run_opts: "--privileged --volume=/sys/fs/cgroup:/sys/fs/cgroup:ro"
    script_opts: "--server-webserver=apache"
  - test: CentOS 7 NGINX
    distribution: centos
    version: 7
    init: /usr/lib/systemd/systemd
    run_opts: "--privileged --volume=/sys/fs/cgroup:/sys/fs/cgroup:ro"
    script_opts: "--server-webserver=nginx"
  - test: Ubuntu 14.04 Apache
    distribution: ubuntu
    version: 14.04
    init: /sbin/init
    run_opts: ""
    script_opts: "--server-webserver=apache"
  - test: Ubuntu 14.04 NGINX
    distribution: ubuntu
    version: 14.04
    init: /sbin/init
    run_opts: ""
    script_opts: "--server-webserver=nginx"

addons:
  hosts:
    - devshop.travis

services:
  - docker

before_install:
  # Pull container
  - 'sudo docker pull ${distribution}:${version}'
  # Customize container
  - 'sudo docker build --rm=true --file=tests/Dockerfile.${distribution}-${version} --tag=${distribution}-${version}:ansible tests'

script:
  - container_id=$(mktemp)
    # Run container in detached state
  - 'sudo docker run --detach --name devshop_container --volume="${PWD}":/etc/ansible/devshop:rw ${run_opts} -h devshop.travis ${distribution}-${version}:ansible "${init}" > "${container_id}"'

  # Ansible syntax check.
  - 'sudo docker exec --tty sd env TERM=bash ansible-playbook /etc/ansible/devshop/playbook.yml --syntax-check'

  # Test install script.
  - 'sudo docker exec --tty devshop_container env TERM=bash /etc/ansible/devshop/install.sh ${script_opts} --hostname=devshop.travis'

  # Test for DevShop.
  - 'sudo docker exec devshop_container sudo su - aegir -c "drush @hostmaster status"'
  - 'sudo docker exec devshop_container sudo su - -c "cd /etc/ansible/devshop/tests && composer update"'
  - 'sudo docker exec devshop_container sudo su - aegir -c "devshop devmaster:test"'
  - 'sudo docker stop devshop_container'
