---
##

language: python
python: "2.7"
install:

  # Install DevShop with the standalone installer, using local playbooks.
  # Run as actual root?  Testing to see if this is a problem.
  - sudo su root -c "bash install.sh"

script:
  - drush @hostmaster uli

# Notify devshop IRC chatroom.
notifications:
  irc: "chat.freenode.net#devshop"
