---
##

language: python
python: "2.7"
install:

  # Install DevShop with the standalone installer, using local playbooks.
  # Run as actual root?  Testing to see if this is a problem.
  - sudo su root -c "bash install.sh"

script:
  - sudo su aegir -c "devshop status"
  - sudo su aegir -c "cd /usr/share/devshop/tests && composer install && bin/behat

  # Test for DevShop
#  - sudo su -c "cd /usr/share/devshop/tests && composer update"
  # Failing build looks pretty bad.  Let's finish this work in a branch.
  # - sudo su aegir -c "cd /usr/share/devshop/tests && bin/behat --profile travis"

# Notify devshop IRC chatroom.
notifications:
  irc: "chat.freenode.net#devshop"
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/5c08b3d3486eed16f82c
    on_success: change
    on_failure: always
    on_start: false