dist: trusty
language: php

branches:
  # Only test the master branch and SemVer tags.
  only:
    - master
    - /^[[:digit:]]+\.[[:digit:]]+\.[[:digit:]]+.*$/

matrix:
  fast_finish: true
  include:
    - php: 7.3
    - php: 7.2
    - php: 7.1
    - php: 7.0

env:
  - TRAVIS_TEST_DIR="$HOME/yaml-tests-tests"

sudo: false

cache:
  directories:
    - $HOME/.composer/cache

install:
  - env

  # tests folder must be outside project.
  - composer install --ansi
  - cp -rf tests $TRAVIS_TEST_DIR
  - cd $TRAVIS_TESTS_DIR
  - composer install --ansi

script:
  - echo "### Testing yaml-tests command script
  - cd $TRAVIS_BUILD_DIR
  - ./yaml-tests --ansi -v --hostname=$TRAVIS_JOB_WEB_URL
  - echo "### Testing yaml-tests composer command
  - cd $TRAVIS_TEST_DIR
  - composer yaml-tests --ansi -v --hostname=$TRAVIS_JOB_WEB_URL

#after_success:
#  - travis_retry php vendor/bin/php-coveralls -v
