---
language: python
python: "2.7"
before_install:
 - sudo apt-get update -qq
 - sudo apt-get install -qq python-apt python-pycurl
install:
  - pip install ansible
script:
  - echo localhost > inventory
  - ansible-playbook -i inventory --syntax-check playbook.yml
  - ansible-playbook -i inventory playbook.yml --connection=local --sudo

  # Check for idempotency
  - ansible-playbook -i inventory playbook.yml --connection=local --sudo
  | grep -q 'changed=0.*failed=0'
  && (echo 'Idempotence test: pass' && exit 0)
  || (echo 'Idempotence test: fail' && exit 1)

  # Test for DevShop
  - curl http://localhost/