dist: trusty
language: php

branches:
  # Only test the master branch and SemVer tags.
  only:
    - master
    - /^[[:digit:]]+\.[[:digit:]]+\.[[:digit:]]+.*$/

matrix:
  fast_finish: true
  include:
    - php: 7.3
    - php: 7.2
    - php: 7.1
    - php: 7.0

sudo: false

cache:
  directories:
    - $HOME/.composer/cache

install:
  - composer install
  - composer global-install provision-ops/yaml-tests:dev-${TRAVIS_BRANCH}

script:
  - composer yaml-tests

#after_success:
#  - travis_retry php vendor/bin/php-coveralls -v
