---
##

language: python
python: "2.7"
install:

  # Install DevShop with the standalone installer, using local playbooks.
  # Run as actual root?  Testing to see if this is a problem.
  - shell: install.sh --server-webserver=nginx
    become: yes
    

script:
  # Run `devshop status` command.
  - command: devshop status
    become: yes
    become_user: aegir

  # Test for DevShop
  # Not quite ready yet.
  #  - cd $TRAVIS_BUILD_DIR/tests && sudo composer install && sudo su aegir -c "bin/behat --profile travis"

# Notify devshop IRC chatroom.
notifications:
  irc: "chat.freenode.net#devshop"
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/5c08b3d3486eed16f82c
    on_success: change
    on_failure: always
    on_start: false

sudo: required
dist: trusty
addons:
  hosts:
    - localhost
