# DevShop Development Dockerfile
version: '3'
services:

  devshop:
    image: "devshop/server:${OS:-ubuntu1804}"
    ports:
      - "80:80"
      - "2222:22"
    hostname: devshop.local.computer
    extra_hosts:
      - "drpl8.testenv.devshop.local.computer:127.0.0.1"
    environment:
      # TODO: Make ansible options easier to alter.
      # @TODO: Change back to devshop.local.computer
      DEVSHOP_DOCKER_COMMAND_RUN: ansible-playbook /etc/ansible/play.yml -vv --tags runtime --extra-vars server_hostname=localhost
    privileged: true
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
      - /var/lib/mysql
      - /var/logs/aegir

      - ./aegir-home:/var/aegir:delegated
      - ./src/DevShop/Templates/DevShopControlTemplate:/var/aegir/devmaster-1.x
      - ./devmaster:/var/aegir/devmaster-1.x/web/profiles/devmaster
      - ./:/usr/share/devshop:delegated
      - $HOME/.ssh:/var/aegir/.ssh
