#
# docker-compose-tests.yml
#
# Only used in CI.  See https://github.com/opendevshop/devshop/actions

version: '2.1'
services:
  # @TODO: Remove this duplication by creating a docker-compose overrides yml file for automated testing that just makes the changes needed.
  devshop:
    image: devshop/server:local
    build:
      context: '.'
      dockerfile: 'Dockerfile.fast'
      args:
      - DEVSHOP_DOCKER_FROM_IMAGE=${DEVSHOP_DOCKER_FROM_IMAGE:-"devshop/server:latest"}
      - ANSIBLE_VERBOSITY=${ANSIBLE_VERBOSITY:-0}
      - DEVSHOP_USER_UID=${DEVSHOP_USER_UID:-1000}

      # @TODO: Cleanup playbooks: Local development, docker container, testing environment.
      # Right now, all systems use the playbook.server.yml playbook.
      # (docker hub, local development, github actions)
      - DEVSHOP_PLAYBOOK=${DEVSHOP_PLAYBOOK:-docker/playbook.server.yml}

    ports:
      - 80:80
    hostname: devshop.local.computer
    extra_hosts:
    - "drpl8.testenv.devshop.local.computer:127.0.0.1"
    env_file:
      - .github/.ci.env

    environment:

      # When using the "devshop-test-upgrade.sh" script, installs this version first.
      UPGRADE_FROM_VERSION: "1.0.0-rc4-testing"
      UPGRADE_FROM_PROVISION_VERSION: "7.x-3.10"

      # Set any desired ansible configuration items here. (Only affects containers at run time, not build time.)
      ANSIBLE_VERBOSITY: 0

      CI: "CI"

      # Add additional files you would like to output in the container logs here, separated by a space.
      DEVSHOP_ENTRYPOINT_LOG_FILES: "/var/log/aegir/*"
      DEVSHOP_TESTS_ASSETS_PATH: "/usr/share/devshop/.github/test-assets"

      # Reads GITHUB TOKEN from the calling environment.
      GITHUB_TOKEN: "${GITHUB_TOKEN}"

    privileged: true
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
      - /var/lib/mysql
      - ./.github/.test-assets:/usr/share/devshop/.github/test-assets