version: '2'

# This compose file is just an example. Create your own to launch your own Aegir cluster

services:

  devmaster:
    image: devshop/devmaster
    ports:
      - 80:80
    hostname: devshop.local.computer
    links:
      - database
    depends_on:
      - database
    environment:
      MYSQL_ROOT_PASSWORD: strongpassword
    volumes:
      # Use direct mounts if you are on Linux
      - ./source/devmaster-1.x:/var/aegir/devmaster-docker
      - ./source/drush:/var/aegir/.drush/commands

      # If you have a mac, it is very slow to have direct volume mounts.
      # We are attempting a workaround by monitoring for changes and copying the files into place.
      - ./source:/volumes

  database:
    image: mariadb
    logging:
      driver: none
    environment:
      MYSQL_ROOT_PASSWORD: strongpassword