# DevShop Development Dockerfile
version: '2.2'
services:

  devshop:
    image: "devshop/server:${OS:-ubuntu1804}"
    ports:
      - "80:80"
      - "2222:22"
    hostname: devshop.local.computer
    extra_hosts:
      - "drpl8.testenv.devshop.local.computer:127.0.0.1"
    command: "${COMMAND:-'echo DevShop Server Online from main docker-compose.yml'}"
    environment:
      DEVSHOP_TEST: x
      # By default, devshop container will run 'ansible-playbook --tags runtime' after running the "command"
      # Keep DEVSHOP_DOCKER_COMMAND_RUN uncommented to use this command to provision the server instead.
      # @TODO: Create single value ENV vars for AEGIR_USER_UID
      ANSIBLE_TAGS: "${ANSIBLE_TAGS:-runtime}"
      ANSIBLE_SKIP_TAGS: "${ANSIBLE_TAGS:-}"
      ANSIBLE_EXTRA_VARS: "${ANSIBLE_EXTRA_VARS:-}"
      ANSIBLE_VERBOSITY: "${ANSIBLE_VERBOSITY:-}"
      ANSIBLE_PLAYBOOK_COMMAND_OPTIONS: --extra-vars @/etc/ansible/vars.yml
      DEVSHOP_DOCKER_COMMAND_RUN: "${DEVSHOP_DOCKER_COMMAND_RUN:-}"

    privileged: true
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
      - /var/lib/mysql
      - /var/logs/aegir

      - ./aegir-home:/var/aegir:delegated
      - ./devmaster:/usr/share/devshop/src/DevShop/Templates/DevShopControlTemplate/web/profiles/devmaster
      - ./:/usr/share/devshop:delegated

      - ./roles/devshop.server/play.yml:/etc/ansible/play.yml

      # This file is used in the default DEVSHOP_DOCKER_COMMAND_RUN.
      - ./vars.development.yml:/etc/ansible/vars.yml
      - ./roles:/etc/ansible/roles

      # NOTE: This will NOT work if docker is installed with Snap. Snaps change HOME for each app: https://snapcraft.io/docs/environment-variables
      # To fix, symlink your ssh dir into the snap/docker/current directory:
      #   ln -s ~/.ssh ~/snap/docker/current
      # @TODO: Detect this situation with the robo up command.
      - $HOME/.ssh:/var/aegir/.ssh

      # To develop the docker-systemd-entrypoint without having to rebuild the container, set this volume.
      - ./docker/bin/docker-systemd-entrypoint:/usr/local/bin/docker-systemd-entrypoint

    # Resource allocation.
    # 4GB, 2CPUs is a good minimum.

    # mem_limit is a hard upper limit for the container.
    # If using linux, make sure this is below your system's idle free memory or your desktop will slow down.
    mem_limit: 10g

    # mem_reservation is a minimum that your system will reserve for the container.
    # DevShop needs about 4GB to provide a good user experience.
    mem_reservation: 4g

    # Restrict the containers to only use the first 2 CPUs
    cpuset: 0,1
