version: '2'

# This compose file is just an example. Create your own to launch your own Aegir cluster

services:

  devshop:
    image: devshop/server:local
    ports:
      - 80:80
    hostname: devshop.local.computer
    environment:
      MYSQL_ROOT_PASSWORD: strongpassword
      AEGIR_MAKEFILE: /usr/share/devshop/build-devmaster-dev.make.yml
      AEGIR_PROFILE: devmaster
      AEGIR_VERSION: 1.x
      TRAVIS: 1
      AEGIR_HOSTMASTER_ROOT: /var/aegir/devmaster-1.x
      XDEBUG_CONFIG: "remote_host=172.17.0.1 idekey=PHPSTORM"
      PHP_IDE_CONFIG: "serverName=devshop.local.computer"
      GITHUB_TOKEN: "${GITHUB_TOKEN}"

      # To allow the devmaster container to launch other docker containers, we need the host's path to aegir home directory.
      HOST_AEGIR_HOME: /home/jon/Projects/devshop/aegir-home

      # Make sure devshop CLI is in the PATH.
      PATH: "/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/usr/share/devshop/bin"

    privileged: true
    volumes:
      - ./aegir-home:/var/aegir:z
      - ./:/usr/share/devshop:z
      - ./provision:/usr/share/drush/commands/provision:z
      - /var/run/docker.sock:/var/run/docker.sock
