# DevShop Development Dockerfile
version: '3'
services:

  devshop:
    image: "devshop/server:${OS:-ubuntu1804}"
    ports:
      - "80:80"
      - "2222:22"
    hostname: devshop.local.computer
    extra_hosts:
      - "drpl8.testenv.devshop.local.computer:127.0.0.1"
    command: echo 'Hello World! DevShop Development Image here. To run as a single process, override 'command' in docker-compose.yml. '
    environment:
      DEVSHOP_TEST: x
      # By default, devshop container will run 'ansible-playbook --tags' runtime after running the "command"
      # Change the DEVSHOP_DOCKER_COMMAND_RUN if you want to manually run commands instead.
      # DEVSHOP_DOCKER_COMMAND_RUN: ansible-playbook /etc/ansible/play.yml --tags runtime --extra-vars @/etc/ansible/vars.yml
      ANSIBLE_VERBOSITY: 1

    privileged: true
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
      - /var/lib/mysql
      - /var/logs/aegir

      - ./aegir-home:/var/aegir:delegated
      - ./src/DevShop/Templates/DevShopControlTemplate:/var/aegir/devmaster-1.x
      - ./devmaster:/var/aegir/devmaster-1.x/web/profiles/devmaster
      - ./:/usr/share/devshop:delegated
      - ./roles/devshop.server/play.yml:/etc/ansible/play.yml
      - ./vars.yml:/etc/ansible/vars.yml
      - ./roles:/etc/ansible/roles
      - $HOME/.ssh:/var/aegir/.ssh
      # To develop the docker-systemd-entrypoint without having to rebuild the container, set this volume.
      - ./docker/bin/docker-systemd-entrypoint:/usr/local/bin/docker-systemd-entrypoint
