version: '2'
services:
  devmaster:
    image: devshop/server:local
    ports:
      - 80:80
    hostname: devshop.local.computer
    environment:
      GITHUB_TOKEN: "${GITHUB_TOKEN}"

    privileged: true
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
