#
# docker-compose.volumes.yml
#
# This dockerfile is for local development only. It maps the development folders to volumes,
#
version: '2.2'
services:
  devshop:
    volumes:
      # Development volumes

      # DevShop Core
      - $PWD:/usr/share/devshop:delegated

      # DevShop Control root
      - ./src/DevShop/Templates/DevShopControlTemplate:/var/aegir/devshop-control-1.x

      # Devmaster Drupal Install Profile
      - ./devmaster:/var/aegir/devshop-control-1.x/web/profiles/devmaster

      # Provision Drush Extension
      - ./provision:/var/aegir/.drush/commands/provision:delegated
      - $HOME/.ssh:/var/aegir/.ssh
