#
# docker-compose.volumes.yml
#
# This dockerfile is for local development only. It maps the development folders to volumes,
#
version: '2.2'
services:
  devshop:
    volumes:
      # Development volumes
      - ./src/DevShop/Templates/DevShopControlTemplate:/var/aegir/devshop-control-1.x
      - $PWD:/usr/share/devshop:delegated
      - ./provision:/var/aegir/.drush/commands/provision:delegated
      - $HOME/.ssh:/var/aegir/.ssh
