version: '2.1'

# This compose file is just an example. Create your own to launch your own Aegir cluster

services:

  devshop:
    image: devshop/server:local
    build:
      context: '.'
      dockerfile: 'Dockerfile'
      args:
      - FROM_IMAGE
      - DEVSHOP_USER_UID

      - ANSIBLE_VERBOSITY
      - ANSIBLE_EXTRA_VARS
      - ANSIBLE_PLAYBOOK
      - ANSIBLE_TAGS
      - ANSIBLE_SKIP_TAGS
      - ANSIBLE_PLAYBOOK_COMMAND_OPTIONS
      - ANSIBLE_CONFIG

      - DRUPAL_MAKEFILE
      - DRUPAL_ROOT

    ports:
      - "80:80"
      - "2222:22"
    hostname: devshop.local.computer
    extra_hosts:
      - "drpl8.testenv.devshop.local.computer:127.0.0.1"
    environment:
      - ANSIBLE_PLAYBOOK
      - ANSIBLE_PLAYBOOK_COMMAND_OPTIONS
      - ANSIBLE_TAGS
      - ANSIBLE_SKIP_TAGS
      - ANSIBLE_VERBOSITY

      # Change to use a different database host.
      - DATABASE_HOST=localhost
      - XDEBUG_CONFIG="remote_host=172.17.0.1 idekey=PHPSTORM"
      - PHP_IDE_CONFIG="serverName=devshop.local.computer"

      # To allow the devmaster container to launch other docker containers, we need the host's path to aegir home directory.
      - HOST_AEGIR_HOME=/home/jon/Projects/devshop/aegir-home


      # Add additional files you would like to output in the container logs here, separated by a space.
      # - DEVSHOP_ENTRYPOINT_LOG_FILES="/var/log/aegir/*"
      # - DEVSHOP_TESTS_ASSETS_PATH="/usr/share/devshop/.github/test-assets"

    privileged: true
    volumes:
      - ./aegir-home:/var/aegir:delegated
      - ./:/usr/share/devshop:delegated
      - ./provision:/usr/share/drush/commands/provision:delegated
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
      - /var/lib/mysql
      - /var/logs/aegir
      - $HOME/.ssh:/var/aegir/.ssh

# Database container is now optional: for local development just use the devshop/server container.
#  database:
#    image: mariadb
#    logging:
#      driver: none
#    environment:
#      MYSQL_ROOT_PASSWORD: strongpassword

#  admin:
#    image: phpmyadmin/phpmyadmin
#    links:
#      - devshop:db
#    ports:
#      - 8080:80

#  selenium:
#    image: selenium/standalone-chrome-debug:3.4.0-dysprosium
#    ports:
#      - 4444:4444
#      - 5900:5900
