#
# docker-compose.volumes.yml
#
# This dockerfile is for local development only. It maps the development folders to volumes,
#
version: '2.2'
services:
  devshop:
    volumes:
      - ./aegir-home:/var/aegir:delegated
      - ./src/DevShop/Templates/DevShopControlTemplate:/var/aegir/devmaster-1.x
      - ./:/usr/share/devshop:delegated
      - ./provision:/usr/share/drush/commands/provision:delegated
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
      - /var/lib/mysql
      - /var/logs/aegir
      - $HOME/.ssh:/var/aegir/.ssh
