site_name: 'Open DevShop'
docs_dir: 'docs'
theme: 'flatly'
pages:
- 'About':
  - 'About DevShop': 'index.md'
  - 'Roadmap': 'roadmap.md'
- 'Installation':
  - 'Installing DevShop': 'install.md'
  - 'Changing Hostname': 'changing-hostname.md'
- 'Architecture':
  - 'Architecture Overview': 'architecture.md'
  - 'Setup Examples': 'examples.md'
- 'Development':
  - 'Developing DevShop': 'development.md'
  - 'Release Process': 'release-process.md'
- 'Management':
  - 'Deleting Projects & Environments': 'deleting.md'
  - 'Using SSL': 'ssl.md'
  - 'Password Protection': 'password-protect.md'
  - 'Remote Servers': 'remotes.md'
  - 'Going Live': 'going-live.md'
  - 'Scaling': 'scaling.md'

