site_name: 'Open DevShop'
docs_dir: 'docs'
theme: 'flatly'
pages:
- 'About':
  - 'About DevShop': 'index.md'
  - 'Roadmap': 'ROADMAP.md'
- 'Installation':
  - 'Installing DevShop': 'INSTALL.md'
  - 'Changing Hostname': 'changing-hostname.md'
- 'Architecture':
  - 'Architecture Overview': 'ARCHITECTURE.md'
  - 'Setup Examples': 'EXAMPLES.md'
- 'Development':
  - 'Developing DevShop': 'DEVELOPMENT.md'
  - 'Release Process': 'release-process.md'
