##
# DevShop
#

---
- hosts: default
  user: root

  vars_files:
    - vars.yml
    - vars.{{ ansible_os_family }}.yml

  tasks:

    - hostname: name={{ server_hostname }}

    # DEBIAN
    - name: Setup | Message of the day.
      action: template src=templates/motd.j2 dest=/etc/update-motd.d/95-ansible mode=755
      when: ansible_os_family == "Debian"

    # REDHAT
    - name: Setup | Message of the day.
      action: template src=templates/motd.j2 dest=/etc/motd mode=755
      when: ansible_os_family == "RedHat"


    # DEBIAN
    - name: Setup | Install required packages.
      action: apt pkg={{ item }} state=installed update_cache=yes
      when: ansible_os_family == "Debian"
      with_items:
        - apache2
        - mysql-server
        - php5
        - php5-cli
        - php5-curl
        - php5-gd
        - php5-mysql
        - php-pear
        - postfix
        - sudo
        - rsync
        - git-core
        - unzip
        - vim
        - git
        - supervisor
        - drush=4.5-6
        - python-mysqldb

    # REDHAT
    - name: Setup | Install required packages.
      action: yum name={{ item }} state=present
      when: ansible_os_family == "RedHat"
      with_items:
#      httpd php php-mysql php-cli php-gd php-process sudo rsync git postfix
        - httpd
        - php
        - php-mysql
        - php-cli
        - php-gd
        - php-process
        - php-pear
        - php-xml
        - postfix
        - sudo
        - rsync
        - git-core
        - unzip
        - vim
        - git
        - cronie
        - mariadb
        - mariadb-server
        - MySQL-python
        - epel-release
        - supervisor

    # REDHAT
    - name: Setup | Install Drush
      include: tasks/drush.yml
      when: ansible_os_family == "RedHat"

    - name: Service | Ensure Supervisor is started and enabled
      service:
        name={{ supervisor_daemon }}
        state=started
        enabled=yes

    - name: Create Aegir user
      user:
        name=aegir
        shell=/bin/bash
        groups={{ apache_user }}
        append=yes
        system=yes
        home=/var/aegir
        move_home=yes
        generate_ssh_key=yes

    - name: Setup SSH config for aegir user.
      template:
        src=templates/ssh-config.j2
        dest=/var/aegir/.ssh/config
        mode=0600
        owner=aegir
        group=aegir

    # DEBIAN only.  RedHat has rewrite enabled by default.
    - name: Enable mod rewrite
      command: a2enmod rewrite
      when: ansible_os_family == "Debian"

    # TODO: Conditional on ubuntu verison. This folder changed in 14.04
    - name: Symbolic link
      file:
        src=/var/aegir/config/apache.conf
        dest={{ apache_confd_path }}
        state=link
        force=yes

    - name: Write php.ini file. # @TODO: Restart apache if changed.
      template:
        src=templates/php.ini.j2
        dest={{ php_ini_path }}
        mode=0644

    - name: Write my.cnf file.
      template:
        src=templates/my.cnf.{{ ansible_os_family }}.j2
        dest={{ mysql_cnf_path }}
        mode=0644

    - name: Ensure MySQL is started and enabled on boot.
      service:
        name={{ mysql_daemon }}
        state=started
        enabled=yes

    - name: Check for secured installation of MySQL
      stat: path=/var/mysql-secured
      register: mysqlsecured

    - name: Install MySQL Securely
      include: ./tasks/mysql-secure.yml
      when: not mysqlsecured.stat.exists

    - name: Add aegir to sudoers for restarting apache.
      template:
        src=templates/sudoers-d-aegir.j2
        dest=/etc/sudoers.d/aegir
        mode=0440

    - name: Create /var/aegir/.drush
      file:
        path=/var/aegir/.drush
        owner=aegir group=aegir mode=0744
        state=directory

    - name: Install drush tools.
      command: drush dl {{ item }}  --destination=/var/aegir/.drush -y --package-handler=git_drupalorg
      sudo: yes
      sudo_user: aegir
      with_items:
        - provision-{{ provision_version }}
        - provision_git-{{ provision_git_version }}
        - devshop_provision-{{ devshop_provision_version }}
        - provision_logs-{{ provision_logs_version }}
        - provision_solr-{{ provision_solr_version }}
        - provision_tasks_extra-{{ provision_tasks_extra_version }}
        - drush_make-6.x-2.3
      args:
        creates: /var/aegir/.drush/drush_make/drush_make.drush.inc

#    - name: Install Devmaster
#      sudo: yes
#      sudo_user: aegir
#      command: drush devshop-install --version={{ devshop_version }} --aegir_db_pass={{ mysql_root_password }} --aegir_db_user=root --makefile={{ devshop_makefile }} --profile=devshop -y
#      args:
#        creates: /var/aegir/devshop-{{ devshop_version }}/index.php

    - name: Supervisor | Set up queue runner script
      template:
        src=templates/hosting-queue-runner.j2
        dest=/usr/bin/hosting-queue-runner
        mode=0700
        owner=aegir
        group=aegir

    - name: Supervisor | Set up supervisor job
      template:
        src=templates/supervisor-hosting-queue-runner.conf.j2
        dest={{ supervisor_conf_path }}/hosting-queue-runner.conf
        mode=0644
      notify:
        - restart supervisor

  handlers:
    - name: restart supervisor
      service:
        name={{ supervisor_daemon}}
        state=restarted

    - name: restart mysql
      service: >
        name={{ mysql_daemon }}
        state=restarted