---
- hosts: ansible_mysql
  roles:
  - aegir.user
  - geerlingguy.mysql
- hosts: ansible_apache
  roles:
  - aegir.apache
  - geerlingguy.php
  - geerlingguy.php-mysql
  - geerlingguy.composer
  - geerlingguy.drush
- hosts: nginx
  roles:
  - aegir.nginx
  - geerlingguy.php
  - geerlingguy.php-mysql
