##
# DevShop: DevMaster Server with Apache
#
# This is the default playbook run by install.sh.
#
# It can be copied and customized to your needs.
#
# Use the --playbook option when running install.sh to use a different playbook.
#
---
- hosts: all
  user: root
  vars:
    php_version: '7.2'
    php_default_version_debian: '7.2'

  pre_tasks:
    # @TODO: Can we move this into the roles? It's not great having to set this.
    - name: Set Debian Family Server Variables
      when:
        - ansible_os_family == 'Debian'
      set_fact:
        mysql_python_package_debian: python3-mysqldb
        ansible_python_interpreter: python3

  roles:
    - role: geerlingguy.repo-remi
      when: ansible_os_family == 'RedHat'

    - opendevshop.users
    - opendevshop.apache
    - geerlingguy.mysql
    - geerlingguy.php-versions
    - geerlingguy.php
    - geerlingguy.php-mysql
    - geerlingguy.composer
    - opendevshop.devmaster
