##
# DevShop: DevMaster Server with Apache
#

---
- hosts: all
  user: root
  roles:
    - opendevshop.user
    - opendevshop.apache
    - geerlingguy.php
    - geerlingguy.php-mysql
    - geerlingguy.composer
