---
- hosts: mysql
  roles:
  - geerlingguy.mysql
#   RedHat uses MariaDB
  vars:
    mysql_daemon: mariadb
    mysql_log_error: /var/log/mariadb/error.log
    mysql_pid_file: /var/run/mariadb/mariadb.pid
    mysql_packages:
      - mariadb
      - mariadb-server
    when: ansible_os_family == "RedHat"
- hosts: apache
  roles:
  - aegir.apache
  - geerlingguy.php
  - geerlingguy.php-mysql
  - geerlingguy.composer
  - geerlingguy.drush
- hosts: nginx
  roles:
  - aegir.nginx
  - geerlingguy.php
  - geerlingguy.php-mysql
