##
# DevShop: DevMaster Server with Apache
#

---
- hosts: all
  user: root
  roles:
    - opendevshop.users
    - opendevshop.apache
    - geerlingguy.php-versions
    - geerlingguy.php
    - geerlingguy.php-mysql
    - geerlingguy.composer
    - opendevshop.devmaster
  vars:

    # Since we are running tests as a process, we don't want tasks to run in the background.
    supervisor_started: false
    supervisor_enabled: false

    ansible_python_interpreter: python3
