##
# DevShop: DevMaster Server with Apache
#

---
- hosts: all
  user: root
  vars:
    php_version: '7.2'
    php_default_version_debian: '7.2'
    ansible_python_interpreter: /usr/bin/python3

  roles:
    - role: geerlingguy.repo-remi
      when: ansible_os_family == 'RedHat'

    - opendevshop.users
    - opendevshop.apache
    - geerlingguy.mysql
    - geerlingguy.php-versions
    - geerlingguy.php
    - geerlingguy.php-mysql
    - geerlingguy.composer
    - opendevshop.devmaster

  pre_tasks:

    - name: Set CentOS7 to use python 2
      when:
        - ansible_os_family == 'RedHat'
        - ansible_distribution_major_version == '7'
      set_fact:
        ansible_python_interpreter: python2