---
- name: Supervisor | Set up queue runner script
  when: supervisor_running
  template:
    src: hosting-queue-runner.j2
    dest: /usr/bin/hosting-queue-runner
    mode: 0700
    owner: "{{ aegir_user_name }}"
    group: "{{ aegir_user_name }}"

- name: Supervisor | Set up supervisor job
  when: supervisor_running
  template:
    src: supervisor-hosting-queue-runner.conf.j2
    dest: "{{ supervisor_hosting_queued_conf_path }}"
    mode: 0644
  notify:
    - restart supervisor

- name: Service | Ensure Supervisor is restarted
  when: supervisor_running
  service:
    name: "{{ supervisor_daemon }}"
    state: restarted
    sleep: 5
    enabled: yes
