---
apache_vhosts_version: "2.2"
apache_ports_configuration_items:
  - {
    regexp: "^Listen ",
    line: "Listen {{ apache_listen_port }}"
  }
  - {
    regexp: "^NameVirtualHost ",
    line: "NameVirtualHost *:{{ apache_listen_port }}"
  }
apache_conf_path: /etc/apache2/conf.d