###
# DevShop Server Container
#
# All-in-one DevShop. Includes all services required to run on one instance.
#
# Container name: devshop/server
#
###
---
- hosts: devshop-server
  become: true

  vars:
    # Hostname must be set when container is launched, which "hostname" option.
    server_hostname: "devshop.local.computer"
    server_hostname_ignore_errors: true

    # The geerlingguy.mysql and opendevshop.devmaster roles both use this
    mysql_root_password: root

    # @TODO: Install multiple versions per-container: https://github.com/oerdnj/deb.sury.org/wiki/Managing-Multiple-Versions
    php_version: "7.2"

    php_default_version_debian: "{{ php_version }}"

    # Needs to be set to false when developing so your code doesn't get updated inside the container on build.
    # Code gets copied using the Dockerfile
    # @TODO: This may not be needed now that the "ancestor" check is in place.
    devshop_cli_update: false

    # This is set to TRUE to ensure the playbooks don't try to run the devmaster upgade every time they run (aka on robo up).
    devmaster_skip_upgrade: true

    # Use Python3.
    # @TODO: This is now set only for Debian systems, in the `pre_tasks` section below..
    # ansible_python_interpreter: python3

    # Supervisor will start when the container and systemd start.
    supervisor_started: false

    # @TODO: Make a cleaner separation between playbooks and makefiles for docker hub, playbooks for CI testing, and local development.s
    # Use local dev makefile because it copies the files directly from this repo.
    # build-devmaster.make is designed for standalone use, and always downloads 1.x until release.
    devshop_makefile: "{{ devshop_cli_path }}/build-devmaster-dev.make.yml"

  pre_tasks:
    - name: Set variables ({{ ansible_os_family}} {{ansible_distribution_major_version}})
      when:
        - ansible_os_family == 'RedHat'
      set_fact:
        apache_state: stopped
        mysql_daemon: mysqld
      tags: [build-time]

    # @TODO: Remove this if ansible_python_interpreter: python3 solves it.
    # @TODO: I was unable to get ubuntu18 installs to properly detect and install the 'mysql_python_package_debian' packages.
    # https://github.com/opendevshop/devshop/pull/518/checks?check_run_id=517865257#step:7:523
    # By default, geerlingguy.mysql loads this automatically. However, in the automated tests for the role, Jeff DOES force set the variable:
    # The automated tests for geerlingguy.mysql set this variable too!
    #   https://github.com/geerlingguy/ansible-role-drupal/blob/master/molecule/default/test-vars.yml#L24
    - name: Set all Debian systems to use python3 as the interpretor, and python3-mysqldb for mysql_python_package_debian.
      when:
        - ansible_os_family == 'Debian'
      set_fact:
        mysql_python_package_debian: python3-mysqldb
        ansible_python_interpreter: python3
      tags: [mysql]

    - name: Set build time variables
      set_fact:
        apache_state: stopped
        mysql_enabled_on_startup: false
      tags: [build-time]

  # All roles have build-time tag here because the build-time tags are used inside the roles. 
  roles:
    - role: geerlingguy.mysql

    - role: geerlingguy.repo-remi
      when: ansible_os_family == 'RedHat'

    - role: opendevshop.apache

    - role: geerlingguy.apache

    - role: geerlingguy.php
   
    - role: geerlingguy.php-versions

    - role: geerlingguy.composer

    - role: opendevshop.devmaster
