---
local_bin_path: /usr/local/sbin
apache_user: apache

# Used to inject date.timezone.
php_cli_ini_path: /opt/rh/php55/root/etc/php.ini

supervisor_daemon: supervisord
supervisor_hosting_queued_conf_path: /etc/supervisord.d/hosting-queue-runner.ini

php_mysql_package: php55-php-mysqlnd

php_packages:
  - php55
#  - php55-php-mysqlnd
  - php55-php-cli
  - php55-php-gd
  - php55-php-process
  - php55-php-pear
  - php55-php-xml
  - php55-php-xmlrpc
#  - php-mcrypt
  - php55-php-mbstring
  - postfix
  - sudo
  - rsync
  - git-core
  - unzip
  - vim
  - git
  - cronie
#  - mariadb
#  - mariadb-server
#  - MySQL-python
# I think this needs to be installed before these packages.
#  - epel-release
  - supervisor
  - openssl
  - mod_ssl
#
#    - php-ldap
#    - php-mbstring
#    - php-opcache
#    - php-pdo
#    - php-pear
#    - php-pecl-apc
#    - php-xml
#    - php-xmlrpc

extra_packages:
  - php55
#  - php55-php-mysqlnd
  - php55-php-cli
  - php55-php-gd
  - php55-php-process
  - php55-php-pear
  - php55-php-xml
  - php55-php-xmlrpc
#  - php-mcrypt
  - php55-php-mbstring
  - postfix
  - sudo
  - rsync
  - git-core
  - unzip
  - vim
  - git
  - cronie
#  - mariadb
#  - mariadb-server
#  - MySQL-python
# I think this needs to be installed before these packages.
#  - epel-release
  - supervisor
  - openssl
  - mod_ssl
  - sendmail