---
- hosts: all
  become: yes

  vars_files:
    - docker-hub-overrides.yml
  vars:

    # Hostname must be set when container is launched, which "hostname" option.
    server_hostname: ''
    php_default_version_debian: 7.3

  roles:
    - opendevshop.users
    - opendevshop.apache
    - geerlingguy.php
    - geerlingguy.php-versions
    - geerlingguy.php-mysql
    - geerlingguy.composer
    - opendevshop.devmaster
