---
- hosts: all
  become: yes

  vars:
    # Hostname must be set when container is launched, which "hostname" option.
    server_hostname: ""

    # @TODO: Install multiple versions per-container: https://github.com/oerdnj/deb.sury.org/wiki/Managing-Multiple-Versions
    php_version: "7.2"
    php_default_version_debian: "{{ php_version }}"

  roles:
    - opendevshop.users
    - opendevshop.apache
    - geerlingguy.php
    - geerlingguy.php-versions
    - geerlingguy.php-mysql
    - geerlingguy.composer
    - opendevshop.devmaster
