---

- name: Include OS-specific variables.
  include_vars: "vars.{{ ansible_os_family }}.yml"

- name: Add aegir to apache group.
  user:
    name: "{{ aegir_user_name }}"
    groups: "{{ apache_user }}"
    append: yes

- name: Install extra packages
  apt:
    pkg: "{{ item }}"
    state: installed
    update_cache: yes
  when: ansible_os_family == "Debian"
  with_items: '{{ extra_packages }}'

- name: Install extra packages
  yum:
    name: "{{ item }}"
    state: present
  when: ansible_os_family == "RedHat"
  with_items: '{{ extra_packages }}'

- name: Install Drush
  get_url:
    url: "https://github.com/drush-ops/drush/releases/download/{{ drush_release_version }}/drush.phar"
    dest: "{{ local_bin_path }}/drush"
    mode: 0755

- name: Install devshop CLI
  git:
    repo: "{{ devshop_cli_repo }}"
    version: "{{ devshop_cli_version }}"
    update: "{{ devshop_cli_update }}"
    dest: "{{ devshop_cli_path }}"

- name: Setup devshop CLI
  command: "{{ composer_path }} install"
  args:
    chdir: "{{ devshop_cli_path }}"

- name: Setup devshop CLI executable
  file:
    src: "{{ devshop_cli_path }}/bin/devshop"
    dest: "{{ local_bin_path }}/devshop"
    state: link
    force: yes

- name: Create /var/aegir/.drush
  file:
    path: "{{ aegir_user_home }}/.drush"
    owner: "{{ aegir_user_name }}"
    group: "{{ aegir_user_name }}"
    mode: 0744
    state: directory

- name: Install required drush packages.
  command: "{{ local_bin_path }}/drush dl {{ item.key }}-{{ item.value }} --destination={{ aegir_user_home }}/.drush/commands --package-handler={{ drush_dl_method }} -y"
  with_dict: "{{ devshop_drush_packages }}"
  become: yes
  become_user: "{{ aegir_user_name }}"

- name: Clear the drush cache.
  command: "{{ local_bin_path }}/drush cc drush"
  become: yes
  become_user: "{{ aegir_user_name }}"

- name: Devmaster Install Command
  debug:
    msg: "{{ devmaster_install_command }}"

- name: Install Devmaster
  become: yes
  become_user: "{{ aegir_user_name }}"
  command: "{{ devmaster_install_command }}"
  args:
    creates: "{{ aegir_user_home }}/.drush/hostmaster.alias.drushrc.php"

- name: Setup Supervisor
  include: "supervisor.yml"