---
- name: Converge
  hosts: all
  become: true

  vars:
    php_opcache_enable: false

  pre_tasks:
    - name: System Information
      debug:
        msg: "Installing on ansible_os_family {{ansible_os_family}} ansible_distribution_major_version {{ansible_distribution_major_version}}"

  roles:
    - role: opendevshop.devmaster
