---
- name: Converge
  hosts: all
  become: true

  vars:
    server_hostname: devshop.local.computer

  pre_tasks:
    - name: Update apt cache.
      apt: update_cache=yes cache_valid_time=600
      when: ansible_os_family == 'Debian'
      changed_when: false

  roles:
    - role: opendevshop.devmaster
