galaxy_info:
  author: Jon Pugh
  description: Installs DevShop Devmaster
  company: OpenDevShop Inc
  min_ansible_version: 2.0
  
  platforms:
    - name: EL
      versions:
      - 7
    - name: Ubuntu
      versions:
      - trusty
      
dependencies:
  - opendevshop.aegir-user
  - opendevshop.apache
  - geerlingguy.mysql
  
  
