install:
  - echo "USE mysql;\nUPDATE user SET password=PASSWORD('password') WHERE user='root';\nFLUSH PRIVILEGES;\n" | mysql -u root
  - sudo sh install.debian.sh

script:
  - wget http://localhost.localdomain/
  - sudo su - aegir -c 'drush @hostmaster status'

# configure notifications (email, IRC, campfire etc)
notifications:
  irc: "chat.freenode.net#devshop"