---
##

language: python
python: "2.7"
install:

  # Install DevShop with the standalone installer, using local playbooks.
  - sudo bash install.sh

script:

  # Test for DevShop
  - curl http://localhost.localdomain/
  - sudo su - aegir -c "drush @hostmaster status"

# Notify devshop IRC chatroom.
notifications:
  irc: "chat.freenode.net#devshop"
