---
- name: Update apt cache.
  apt: update_cache=yes cache_valid_time=86400

- name: Ensure mysql packages are installed.
  apt: "name={{ item }} state=installed"
  with_items: mysql_packages
  when: install_mysql

- name: Ensure apache packages are installed.
  apt: "name={{ item }} state=installed"
  with_items: apache_packages
  when: install_apache