---
- name: Install epel-release
  yum:
    name: "epel-release"
    state: installed

- name: Ensure packages are installed.
  yum:
    name: "{{ item }}"
    state: installed
  with_items: aegir_packages