
  name: devshop
  version: '1.x'
  summary: Drupal DevOps Platform: Develop, Test, & Deploy any Drupal site.
  description: DevShop automates Drupal hosting, testing, and deployment. Press a button, get a copy of your site. Submit a pull request, get a copy of your site. Push your code, automatically deploy and test it.

  grade: devel # must be 'stable' to release into candidate/stable channels
  confinement: devmode # use 'strict' once you have the right plugs and slots

  
