---
##
# Install drush
#
# This is only used for RedHat family.  Debian uses the apt package.

- name: Drush | Setup PEAR channel
  command: pear channel-discover pear.drush.org
    creates=/var/lib/pear/.channels/pear.drush.org.reg

- name: Drush | Install Console_Table
  command: pear install Console_Table
    creates=/usr/share/tests/pear/Console_Table

- name: Drush | Install drush
  command: pear install drush/drush-4.6.0
    creates=/usr/bin/drush

- name: Drush | Run drush once so it downloads it's dependencies
  command: drush --version
