name: Ansible Roles

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-python@v1

# @TODO: Attempted to cache the pip packages, doesn't seem to work in subfolders.
#      - uses: actions/cache@v1
#        id: cache
#        with:
#          path: .cache/pip
#          key: ${{ runner.os }}-pip-${{ hashFiles('**/roles/opendevshop.devmaster/molecule/requirements.txt') }}
#          restore-keys: |
#                ${{ runner.os }}-test

      - name: Install Ansible Molecule
        if: steps.cache.outputs.cache-hit != 'true'
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
        working-directory: roles/opendevshop.devmaster/molecule

      - name: Run `molecule test`
        working-directory: roles
        run: molecule test