name: Ansible Roles

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-python@v1
      - name: Install Ansible Molecule
        run: |
          python -m pip install --upgrade pip
          pip install molecule docker
      - name: Run `molecule test`
        run: |
          cd molecule
          molecule test