name: Composer Install & Split Monorepo

on: [push]

jobs:
  build:

    runs-on: [ubuntu-16.04]

    steps:
    - uses: actions/checkout@v1

    - name: Validate composer.json and composer.lock
      run: composer validate

    - name: Install dependencies
      run: composer install --prefer-dist --no-progress --no-suggest

    - name: Split Git Repositories
      run: bin/monorepo-builder split --config=monorepo-github-actions.yml

    # Add a test script to composer.json, for instance: "test": "vendor/bin/phpunit"
    # Docs: https://getcomposer.org/doc/articles/scripts.md

    # - name: Run test suite
    #   run: composer run-script test
