name: "Components"

on:
  push:
  pull_request:
    types: [opened, synchronize]

# Set working directory for entire file. https://github.community/t5/GitHub-Actions/use-working-directory-for-entire-job/td-p/36759
env:
  working-directory: ./src/DevShop/Component/YamlTasks

jobs:
  yaml-tasks:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Get Composer Cache Directory
      working-directory: ${{env.working-directory}}
      id: composer-cache
      run: |
        echo "::set-output name=dir::$(composer config cache-files-dir)"

    - uses: actions/cache@v1
      with:
        path: ${{ steps.composer-cache.outputs.dir }}
        key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
        restore-keys: |
          ${{ runner.os }}-composer-

    - name: Validate composer.json and composer.lock
      working-directory: ${{env.working-directory}}
      run: composer validate

    - name: Install dependencies
      working-directory: ${{env.working-directory}}
      run: composer install --prefer-dist --no-progress --no-suggest

    - name: Create a branch for the yaml-tests to read.
      working-directory: ${{env.working-directory}}
      run: git checkout -b $( echo ${GITHUB_REF} | sed 's/refs\/heads\///')

    - name: Run Yaml Tests
      working-directory: ${{env.working-directory}}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        # @TODO: Get environment variable setting to work.
        # YAML_TASKS_STATUS_URL: https://github.com/${GITHUB_REPOSITORY}/runs/${GITHUB_RUN_ID}?check_suite_focus=true
        PROVISION_PROCESS_OUTPUT: direct
      run: |
        chmod +x yaml-tasks
        ./yaml-tasks  --ansi -v --hostname=github.com --status-url=https://github.com/${GITHUB_REPOSITORY}/actions/runs/${GITHUB_RUN_ID}?check_suite_focus=true
        ./yaml-tasks --tasks-file tests.yml --ansi -v --hostname=github.com --status-url=https://github.com/${GITHUB_REPOSITORY}/actions/runs/${GITHUB_RUN_ID}?check_suite_focus=true


