name: DevShop Build & Test

on:
  push:
    branches: 1.x
  pull_request:
    types: [opened, synchronize]
  schedule:
    - cron: "0 6 * * *"

env:
  GITHUB_TOKEN: ${{ secrets.INPUT_GITHUB_TOKEN }}
  GITHUB_PR_NUMBER: ${{ github.event.pull_request.number }}
  GITHUB_PR_SHA: ${{ github.event.pull_request.head.sha  }}
  GITHUB_RUN_LOG_URL: https://github.com/opendevshop/devshop/actions/runs/${{ github.run_id }}

jobs:
  docker:
    name: "Docker Containers"
    # description: Build every docker container, then install DevShop to confirm they work.
    strategy:
      fail-fast: false
      matrix:
        os:
          - 'ubuntu1804'
          - 'centos7'
    env:
      OS: "${{ matrix.os }}"
      HOSTNAME: "devshop.${{ github.event.pull_request.number }}.${{ matrix.os }}.actions.github.com"

    runs-on: ubuntu-latest
    steps:

      - name: Check Out Sourcecode
        uses: actions/checkout@v2

      # Build "base"
      - name: "Build: devshop/base:${{ matrix.os }}"
        working-directory: docker
        run: docker-compose build base

      # Build "ansible"
      - name: "Build: devshop/ansible:${{ matrix.os }}"
        working-directory: docker
        run: docker-compose build ansible

      # Build "core"
      - name: "Build: devshop/core:${{ matrix.os }}"
        working-directory: docker
        run: docker-compose build core

      # Build "role"
      - name: "Build: devshop/role:${{ matrix.os }}"
        working-directory: docker
        run: docker-compose build role

      # Build DevShop Role Images
      - name: "Build all DevShop Roles (${{ matrix.os }})"
        working-directory: roles
        run: docker-compose build

      # Launch Container
      - name: "Launch: devshop/server:${{ matrix.os }}"
        working-directory: roles
        run: docker-compose up devshop.server

      - name: Save Assets
        if: always()
        env:
          IMAGE: "ansible"
          DOCKER_IMAGE: "devshop/server:${{ matrix.os }}-local"
          DOCKER_CONTAINER: "devshop-server-${{ matrix.os }}"
        run: |
          docker exec ${DOCKER_CONTAINER} systemctl status --no-pager | tee ./.github/test-assets/systemctl-status.log
          docker logs ${DOCKER_CONTAINER} | tee ./.github/test-assets/docker-container.log


  devmaster:
    name: Devmaster 
    # description: Install devmaster and run tests on a pre-built image.
    # @TODO: Set up this job once the devshop/server container is done.
    if: false
    runs-on: ubuntu-latest
    container:
      image: devshop/ansible:centos7
      volumes:
        - ./:/usr/share/devshop
      options: >-
        --hostname={{ env.HOSTNAME }}

    steps:

      - name: Check Out Sourcecode
        uses: actions/checkout@v2

      - name: Install devmaster
        run: devhop devmaster:install

      - name: Test devmaster
        run: devhop devmaster:test                
