name: Build DevShop Server Container

on: [push]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Build the DevShop Server Docker image
      run: docker build . --file Dockerfiles/Dockerfile --tag devshop/server:$GITHUB_SHA

    - name: Run DevShop Server and tests
      run: docker run devshop/server:$GITHUB_SHA /usr/share/devshop/tests/run-tests.sh
