name: Build DevShop Server Container

on: [push]

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - name: Cache composer cache directory
      uses: actions/cache@v1
      with:
        path: .gh-actions-composer-cache
        key: 'composer-cache'

    - name: Install dependencies
      run: composer install --prefer-dist --no-progress --no-suggest

    - name: Build the DevShop Server Docker image
      run: bin/robo prepare:containers

    - name: Run DevShop Server and tests
      run: bin/robo up --test