name: Build DevShop Server Container

on: [push]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Build the DevShop Server Docker image
      working-directory: ./Dockerfiles
      run: docker build . --file Dockerfile --tag devshop/server:$(date +%s)

    - name: Run DevShop Server and tests
      run: docker run devshop/server:$(date +%s) /usr/share/devshop/tests/run-tests.sh
