name: Build DevShop Server Container

on: [push]

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - name: Build the DevShop Server Docker image
      run: docker build . --tag devshop/server:$GITHUB_SHA --add-host devshop.local.computer:127.0.0.1

    - name: Run DevShop Server and tests
      run: |
        docker run --name devshop --hostname devshop.local.computer --detach --env GITHUB_TOKEN=$GITHUB_TOKEN devshop/server:$GITHUB_SHA
        docker exec -ti devshop /usr/share/devshop/tests/devshop-tests.sh