name: Install Script
on: [push]

strategy:
  matrix:
    # @see https://hub.docker.com/u/geerlingguy/
    # Pattern must match available image name "geerlingguy/docker-*-ansible".
    # ie. https://hub.docker.com/r/geerlingguy/docker-ubuntu1804-ansible
    GEERLINGGUY_DISTRO:
      # - centos7
      # - ubuntu1604
      - ubuntu1804

jobs:

  build:

    runs-on: ubuntu-18.04

    steps:
    - name: Prepare Code
      uses: actions/checkout@v1

    - name: Prepare Dependencies
      run: composer install --prefer-dist --no-progress --no-suggest

    - name: Test Install
      run: |
        bin/robo up --mode=install.sh --install-sh-image=geerlingguy/docker-${GEERLINGGUY_DISTRO}-ansible --test --disable-xdebug --non-interactive
