name: Install Script

on:
  push:
    branches: 1.x
  pull_request:
    types: [opened, synchronize]
  schedule:
    # Once per day. https://crontab.guru/#*_0_*_*_*
    - cron: "* 0 * * *"
jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu:18.04
          - centos:7

    runs-on: ubuntu-latest
    container: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - name: Run install.sh
        run: bash install/install.sh --hostname=actions.github.com --playbook=roles/server.playbook.yml
