name: Install
on: [push]
env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
jobs:
  install:
    name: Shell Script
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v1

    - name: Run install.sh Script
      run: sudo -H bash install.sh --playbook=playbook.testing.yml --hostname=devshop.local.computer

    - name: Run tests/devshop-tests.sh Script
      run:  sudo su aegir -c "bash tests/devshop-tests.sh"
