name: Install Script
on: [push]
env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
jobs:
  build:
    runs-on: ubuntu-18.04
    strategy:
      matrix:
        # @see https://hub.docker.com/u/geerlingguy/
        # Pattern must match available image name "geerlingguy/docker-*-ansible".
        # ie. https://hub.docker.com/r/geerlingguy/docker-ubuntu1804-ansible
        GEERLINGGUY_DISTRO:
          # - centos7
          # - ubuntu1604
          - ubuntu1804

    steps:
    - name: Prepare Code
      uses: actions/checkout@v1

    - name: Composer Install
      run: composer install --prefer-dist --no-progress --no-suggest

    - name: Run install.sh Script
      run: |
        bin/robo up --mode=install.sh --install-sh-image=geerlingguy/docker-${GEERLINGGUY_DISTRO}-ansible --test --disable-xdebug --no-interaction
