name: Install Script

on:
  push:
    branches: 1.x
  pull_request:
    types: [opened, synchronize]
  schedule:
    # Once per day. https://crontab.guru/#*_0_*_*_*
    - cron: "* 0 * * *"
jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu1804
          - centos7
        include:
          - os: ubuntu1804
            entrypoint: /lib/systemd/systemd
          - os: centos7
            entrypoint: /usr/lib/systemd/systemd

    runs-on: ubuntu-latest
    container:
      image: geerlingguy/docker-${{ matrix.os }}-ansible
      options: "--privileged --entrypoint=${{ matrix.entrypoint }}"
      volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro

    steps:
      - uses: actions/checkout@v2

      # This is only replicating what the geerlingguy/docker-*-ansible do.
      # - name: Run docker-systemd-prepare
      - name: Run install.sh
        run: bash install/install.sh --hostname=actions.github.com --playbook=roles/server.playbook.yml

#  publish:
#    runs-on: ubuntu-latest
#    steps:
#      - uses: actions/checkout@v2
#      - name: Build html files
#        run: |
#          git checkout gh-pages
#          cp install/install.sh install/index.html
#          git commit install/index.html -m "Committing install script as index.html"
#          git push
