name: Install
on: [push]
env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
jobs:
  install:
    name: Shell Script
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v1

    - name: Run install.sh Script
      run: bash install.sh --hostname=devshop.local.computer

    - name: Run tests/devshop-tests.sh Script
      run: bash tests/devshop-tests.sh --hostname=devshop.local.computer
