# Workflows that publish things

name: Publish

on:
  push:
    branches: [ 1.x ]
  pull_request:
    
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
 publish:
    runs-on: ubuntu-latest
    steps:
    -
      name: Checkout
      uses: actions/checkout@v2
    -
      name: Build
      run: |
        cd install
        cp install.sh index.html 
    -
      name: Deploy
      if: success()
      uses: crazy-max/ghaction-github-pages@v1
      with:
        repo: opendevshop/devshop-install
        target_branch: gh-pages
        build_dir: install
      env:
        GITHUB_TOKEN: ${{ secrets.INPUT_GITHUB_TOKEN }}
        GITHUB_PAT: ${{ secrets.INPUT_GITHUB_TOKEN }}
